name: cineverse
services:
  mysql:
    container_name: mysql_cineverse
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=cineverse'
      - 'MYSQL_ALLOW_EMPTY_PASSWORD=yes'
    ports:
      - '3306:3306'