export interface MovieCredits {
  cast: string[],
  director: string,
  assistantDirector: string,
  writer: string,
  costumeDesign: string,
  composer: string,
  cinematography: string,
  lighting: string,
  setDecoration: string[],
  stunts: string[],
  visualEffects: string[],
  addDirector: string,
  sound: string[],
  cameraOperators: string[],
  makeup: string,
  hairstyling: string[],
  casting: string[],
  editor: string,
  producers: string[],
  execProducers: string[]
}
